version: "3"
services:
  mysql:
    image: mongo:latest
    container_name: mongo.docker.local
    ports:
      - 27017:27017
    volumes:
      - spring-boot-webflux-rest-mongo:/var/lib/mysql
    networks:
      - spring-boot-webflux-rest-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

volumes:
  spring-boot-webflux-rest-mongo:

networks:
  spring-boot-webflux-rest-mongo:
